version: 2
jobs:
  build:
    working_directory: ~/tts-bug-bounty-dashboard
    docker:
      - image: circleci/python:3.6.8
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=pg
          - POSTGRES_DB=db

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            . venv/bin/activate
            flake8
            pytest
          environment:
            H1_API_USERNAME: testing
            H1_API_PASSWORD: test123
            DEBUG: yup
            DATABASE_URL: postgres://pg:@127.0.0.1:5432/db

      - store_artifacts:
          path: test-reports/
          destination: tr1
