# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disclosed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
