# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_report_disclosed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singletonmetadata',
            options={'verbose_name': 'dashboard settings', 'verbose_name_plural': 'dashboard settings'},
        ),
        migrations.AlterField(
            model_name='singletonmetadata',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the dashboard was last synced with HackerOne. This field generally is not intended for editing, but you can clear it to ensure that the next scheduled sync refreshes all data, which can be useful if the dashboard somehow becomes out-of-sync with HackerOne.', null=True),
        ),
    ]
