# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_update_singleton_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='issue_tracker_reference_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
