# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_report_issue_tracker_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weakness',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
