# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_report_weakness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='USD', max_digits=8)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, help_text='USD', max_digits=8, null=True)),
                ('created_at', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='dashboard.Report')),
            ],
            options={
                'verbose_name': 'bounty',
                'verbose_name_plural': 'bounties',
            },
        ),
    ]
